# Generated by Django 4.2.16 on 2024-10-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.IntegerField()),
                ("product_name", models.CharField(max_length=256)),
                ("user_name", models.CharField(max_length=256)),
                ("restaurant_name", models.CharField(max_length=256)),
                ("quantity", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "index_together": {
                    ("restaurant_name", "created_at"),
                    ("user_name", "product_name"),
                },
            },
        ),
    ]
