# Generated by Django 4.2.16 on 2024-10-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
